export type ClaimType= 'MOTOR' | 'PROPERTY';

export type ClaimStatus=
  | 'SUBMITTED'
  | 'UNDER_REVIEW'
  | 'INFO_REQUESTED'
  | 'APPROVED'
  | 'REJECTED';

export interface Claim {
  id?: string;
  referenceNumber: string;
  claimType: ClaimType;
  claimantName: string;
  claimantEmail: string;
  incidentDate: string;
  description: string;
  estimatedLoss: number;
  status: ClaimStatus;
  assignedOfficer: string | null;
  createdAt: string;
  additionalInformation?: string;
  informationProvidedAt?: string;
}

// note: id is optional because it will be generated by the backend when a new claim is created
// the assigned officer can either contain a name or be null if the claim has not been assigned to an officer yet